name: Build Archlinux Packages

on:
  push:
    branches: [main]
  # schedule:
  #   - cron: "0 1,13 * * 1-6" # build pkgs via 996 rules (；′⌒`), UTC time - 8
  workflow_dispatch: # allow manual trigger

env:
  TZ: America/Lima

jobs:
  Build: # build packages
    strategy:
      matrix:
        pkgs: [
            alberta,
            ampi-openmpi,
            arpackpp,
            charm++-openmpi,
            exam-terminal,
            imagine-git,
            jupyter-gnuplot_kernel,
            psurface,
            python-aabbtree,
            python-accupy,
            python-adaptmesh,
            python-colorio,
            python-colour-science,
            python-cplot,
            python-genpy,
            python-gmsh_interop,
            python-krylov,
            python-krypy,
            python-lsq-ellipse,
            python-meshplex,
            python-meshpy,
            python-meshzoo,
            python-microstructpy,
            python-mplx,
            python-multiprocess,
            python-mystic,
            python-ndim,
            python-npx,
            python-optimesh,
            python-orthopy,
            python-pacopy,
            python-pathos,
            python-pep8,
            python-perfplot,
            python-ppft,
            python-pyamg,
            python-pyfma,
            python-pyfvm,
            python-pygmsh,
            python-pyina,
            python-pykry,
            python-pytest-cache,
            python-pytest-codeblocks,
            python-pytest-flakes,
            python-pytest-pep8,
            python-pyvoro-mmalahe,
            python-quadpy,
            python-requests-cache,
            python-requests-cache-git,
            python-scikit-fem,
            python-scipyx,
            python-termplotlib,
            python-triangle,
            python-umap-learn,
            python-url-normalize,
            python-vapory,
            python-viscm,
            python-yep,
            qtcreator-template-dtk,
            snapgene-viewer,
            zoltan,
          ] # package list
      fail-fast: false # allow package build fails
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Build pkgs in above list
        uses: zjuyk/pkgbuild-aur@master
        with:
          pkg-name: ${{ matrix.pkgs }}
      # - name: Upload assets to release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     allowUpdates: true
      #     tag: "packages"
      #     artifacts: "./*/*.zst"
      #     token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Send notify to telegram
      #   uses: appleboy/telegram-action@master
      #   with:
      #     to: ${{ secrets.TELEGRAM_TO }}
      #     token: ${{ secrets.TELEGRAM_TOKEN }}
      #     format: markdown
      #     message: |
      #       From ${{ github.repository }} - ${{ github.workflow }}:
      #           Package ${{ matrix.pkgs }} build success!
      #       [View it On Github](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
