name: Build Archlinux Packages

on:
  push:
    branches: [main]
  # schedule:
  #   - cron: "0 1,13 * * 1-6" # build pkgs via 996 rules (；′⌒`), UTC time - 8
  workflow_dispatch: # allow manual trigger

env:
  TZ: America/Lima

jobs:
  Build: # build packages
    strategy:
      matrix:
        pkgs: [
            air-bin,
            alberta,
            allure-commandline,
            altermime,
            ampi-openmpi,
            ampl-asl,
            ampl-mp,
            arpackpp,
            autogit,
            blacksheepwall,
            broken-link-checker,
            charm++-openmpi,
            cmakew,
            dynd,
            exam-terminal,
            halide-bin,
            hypre,
            imagine-git,
            jupyter-gnuplot_kernel,
            oneshot-bin,
            otf-asana-math,
            otf-cm-unicode,
            otf-gfs-neohellenic-math,
            otf-textfonts,
            paddleocr-git,
            paddlepaddle-bin,
            pdfquirk,
            pdfquirk-git,
            picapport,
            picopt,
            psurface,
            python-aabbtree,
            python-accupy,
            python-adaptmesh,
            python-allure-commons,
            python-baidubce,
            python-blaze,
            python-codepy,
            python-colorio,
            python-colour-science,
            python-cplot,
            python-datashader,
            python-datatile,
            python-dmsh,
            python-dynd,
            python-elasticsearch-dsl,
            python-felupe,
            python-flake8-builtins,
            python-flake8-class-newline,
            python-flake8-import-order,
            python-genpy,
            python-gmsh_interop,
            python-holoviews,
            python-hvplot,
            python-islpy,
            python-krylov,
            python-krypy,
            python-lsq-ellipse,
            python-lxc,
            python-matadi,
            python-matplotx,
            python-meshplex,
            python-meshpy,
            python-meshzoo,
            python-microstructpy,
            python-multiprocess,
            python-mwoauth,
            python-mystic,
            python-ndim,
            python-npx,
            python-odo,
            python-optimesh,
            python-orthopy,
            python-outdated,
            python-pacopy,
            python-panel,
            python-pathos,
            python-pep8,
            python-perfplot,
            python-ppft,
            python-py-pde,
            python-pyamg,
            python-pydub,
            python-pyfma,
            python-pyfvm,
            python-pygmsh,
            python-pyina,
            python-pyrate-limiter,
            python-pytaglib,
            python-pytest-base-url,
            python-pytest-cache,
            python-pytest-codeblocks,
            python-pytest-flakes,
            python-pytest-pep8,
            python-pytest-selenium,
            python-pytest-variables,
            python-pyvoro-mmalahe,
            python-pywikibot,
            python-quadpy,
            python-rasterio,
            python-requests-cache,
            python-requests-cache-git,
            python-scikit-fem,
            python-scipyx,
            python-snuggs,
            python-spatialpandas,
            python-termplotlib,
            python-triangle,
            python-ufl-git,
            python-umap-learn,
            python-url-normalize,
            python-vapory,
            python-viscm,
            python-yep,
            qtcreator-template-dtk,
            seclists,
            selenoid-bin,
            snapgene-viewer,
            sol2,
            soundcloud-syncer,
            superlu_dist,
            texlive-minionpro-git,
            tiptop-cli,
            visualdl,
            vst-video-bin,
            zoltan,
          ] # package list
      fail-fast: false # allow package build fails
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Build pkgs in above list
        uses: zjuyk/pkgbuild-aur@master
        with:
          pkg-name: ${{ matrix.pkgs }}
      # - name: Upload assets to release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     allowUpdates: true
      #     tag: "packages"
      #     artifacts: "./*/*.zst"
      #     token: ${{ secrets.GITHUB_TOKEN }}
      - name: Send notify to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            From ${{ github.repository }} - ${{ github.workflow }}:
                Package ${{ matrix.pkgs }} build success!
            [View it On Github](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
